//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::sea_orm_active_enums::RewardType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub clan_id: Uuid,
  #[sea_orm(column_type = "Text")]
  pub discord_event_id: String,
  #[sea_orm(column_type = "Text")]
  pub author_id: String,
  pub awardees: Vec<String>,
  pub reward_type: Option<RewardType>,
  pub reward_data: Option<String>,
  pub concluded_by: Uuid,
  pub concluded_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::clan::Entity",
    from = "Column::ClanId",
    to = "super::clan::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Clan,
}

impl Related<super::clan::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Clan.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
