//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role_level")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub clan_id: Uuid,
  #[sea_orm(column_type = "Text")]
  pub name: String,
  #[sea_orm(column_type = "Text")]
  pub description: String,
  #[sea_orm(column_type = "Text")]
  pub discord_role_id: String,
  pub p_direct_ranking: bool,
  pub p_ranking_request: bool,
  pub p_exile_access: bool,
  pub p_medal_access: bool,
  pub p_xp_access: bool,
  pub p_xp_requests: bool,
  pub p_events_access: bool,
  pub p_events_admin: bool,
  pub p_change_shout: bool,
  pub p_join_requests_access: bool,
  pub p_join_requests_admin: bool,
  pub p_bulk_requests: bool,
  pub p_administrator: bool,
  pub ranking_range_min: i32,
  pub ranking_range_max: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::clan::Entity",
    from = "Column::ClanId",
    to = "super::clan::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Clan,
}

impl Related<super::clan::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Clan.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
