//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  #[sea_orm(column_type = "Text", unique)]
  pub discord_id: String,
  #[sea_orm(unique)]
  pub roblox_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::clan_user::Entity")]
  ClanUser,
}

impl Related<super::clan_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::ClanUser.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
